apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: aws-secret-reader-secret
          secretAccessKeySecretRef:
            key: secret
            name: aws-secret-reader-secret
      region: ap-southeast-1
      service: SecretsManager
