# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
apiVersion: batch/v1
kind: CronJob
metadata:
  name: base-cron
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: jobname
              image: base-image
              envFrom:
                - configMapRef:
                    name: base-cm
                - secretRef:
                    name: base-secret
              resources:
                requests:
                  cpu: 100m
                  memory: 500Mi
                limits:
                  cpu: 500m
                  memory: 1Gi
          imagePullSecrets:
            - name: regcred
          volumes: []
          restartPolicy: OnFailure

