apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: base-es
spec:
  dataFrom:
  - extract:
      key: ""
  refreshInterval: 0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: ""
